### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by milaq** [milaq/YCast#13]
Some may find the deployment cumbersome. Create a nice docker image for those.

**Comment by mnasec** [comment]
Hi Milaq,
attached you will find a basic dockerfile for building a ycast container: 
`#docker build --compress -f ycast-dockerfile-v6 -t yourrepository/ycast-docker:v6 .

FROM alpine:latest

#Variables
#YC_VERSION version of ycast software
#YC_STATIONS path an name of the indiviudual stations.yml e.g. /ycast/stations/stations.yml
#YC_DEBUG turn ON or OFF debug output of ycast server else only start /bin/sh
#YC_PORT port ycast server listens to, e.g. 80
ENV YC_VERSION 1.0.0
ENV YC_STATIONS /opt/ycast/stations.yml
ENV YC_DEBUG OFF
ENV YC_PORT 80

RUN apk --no-cache update && \
    apk --no-cache upgrade && \
    apk add --no-cache python3 && \
    apk add --no-cache zlib-dev && \
    apk add --no-cache jpeg-dev && \
    apk add --no-cache build-base && \
    apk add --no-cache python3-dev && \
    pip3 install --no-cache-dir requests && \
    pip3 install --no-cache-dir flask && \
    pip3 install --no-cache-dir PyYAML && \
    pip3 install --no-cache-dir Pillow  && \
    mkdir /opt/ycast && \
    apk del python3-dev && \
    apk del build-base && \
    apk del zlib-dev && \
    apk add --no-cache curl && \
    curl -L https://github.com/milaq/YCast/archive/$YC_VERSION.tar.gz \
    | tar xvzC /opt/ycast && \
    apk del curl
WORKDIR /opt/ycast/YCast-$YC_VERSION
COPY bootstrap.sh /opt
EXPOSE 80/tcp
ENTRYPOINT ["/opt/bootstrap.sh"]
`
and the responding bootstrap.sh:
`#!/bin/sh

#Bootstrap File für ycast docker container
#Variables
#YC_VERSION version of ycast software
#YC_STATIONS path an name of the indiviudual stations.yml e.g. /ycast/stations/stations.yml
#YC_DEBUG turn ON or OFF debug output of ycast server else only start /bin/sh
#YC_PORT port ycast server listens to, e.g. 80

if [ "$YC_DEBUG" = "OFF" ]; then
	/usr/bin/python3 -m ycast -c $YC_STATIONS -p $YC_PORT

elif [ "$YC_DEBUG" = "ON" ]; then
	/usr/bin/python3 -m ycast -c $YC_STATIONS -p $YC_PORT -d

else
	/bin/sh

fi
`

works for me to build the container with your actual code of ycast 1.0.0.

**Comment by mnasec** [comment]
Hi Milaq,
attached you will find a basic dockerfile for building a ycast container. The container will be about 76MB and is based von alpine linux. It builds the container based on your ycast 1.0.0 you released today.
Just put both files in a directory an build your own image.
It works for me on the synology NAS also.

`#docker build --compress -f ycast-dockerfile-v6 -t yourrepro/ycast-docker:v6 .`

[ycast-docker.zip](https://github.com/milaq/YCast/files/3668034/ycast-docker.zip)

**Comment by milaq** [comment]
Thanks :+1: 
I'll have a look at it.

**Comment by mnasec** [comment]
Hi Milaq,
i optimized the image and deleted all unnecessary stuff out of the image, include the *.pyc files, they will be recreated during runtime. Now the image is about 40MB as a tar file using this dockerfile:
[ycast-docker-v9.zip](https://github.com/milaq/YCast/files/3680160/ycast-docker-v9.zip)
Attached you will find the file as tar.gz:
[ycast-docker-v9.tar.gz](https://github.com/milaq/YCast/files/3680172/ycast-docker-v9.tar.gz)

CU

**Comment by MaartenSanders** [comment]
Hi Milaq, mnasec,

Excellent work. I posted a docker image in docker hub (https://hub.docker.com/r/netraams/ycast-docker. Had to make one small change to the permissions of bootstrap.sh

[](url)

**Comment by Yocee84** [comment]
Hi! Please write step by step he install.

I use docker in Synology. 
I found the image. I installed with no lucky. We need special settings? ( especially the volume and the install path? what is it?) 
or we need a simple install? But when i ssh to syno as root, cant fint anything in ycast in opt.

**Comment by MaartenSanders** [comment]
Hi Yocee84,
I don't have a Synology but just a regular docker install.

The container folder /opt/ycast/stations is linked to host folder /mnt/data/docker_appdata/ycast/opt/ycast
in the host folder I have one file: stations.yml with contents:


Nederlandse radio:
  NPO Radio 1: http://icecast.omroep.nl/radio1-bb-mp3
  NPO Radio 2: http://icecast.omroep.nl/radio2-bb-mp3
  NPO Radio 3: http://icecast.omroep.nl/3fm-bb-mp3
  NPO Radio 4: http://icecast.omroep.nl/radio4-bb-mp3
  BNR: http://icecast-bnr.cdp.triple-it.nl/bnr_mp3_128_03
  Sky Radio: http://19993.live.streamtheworld.com/SKYRADIO.mp3
  Qmusic: http://icecast-qmusicnl-cdp.triple-it.nl/Qmusic_nl_live_96.mp3
  Radio 10: http://stream.radio10.nl/radio10

Electronic:
  Deep House Lounge: http://198.15.94.34:8006
  Ibiza Sonica: http://s1.sonicabroadcast.com:7005/stream
  Bassdrive: http://50.7.98.106:8200
  SomaFM Fluid: http://ice1.somafm.com/fluid-128-mp3

Chillout:
  Joint Radio: http://radio.jointil.net:9998
  SomaFM DEF CON Radio: http://ice1.somafm.com/defcon-256-mp3
  SomaFM Drone Zone: http://ice1.somafm.com/dronezone-256-mp3
  SomaFM Mission Control: http://ice1.somafm.com/missioncontrol-128-mp3
  The Jazz Groove: http://west-mp3-128.streamthejazzgroove.com
  Radionomy Downbeat: http://streaming.radionomy.com/TempoOfTheDownbeat1

Casual:
  76Radio: http://192.240.102.133:9566/stream
  SomaFM Beat Blender: http://ice1.somafm.com/beatblender-128-mp3
  Jazz Radio Electro Swing: http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3
  SomaFM Groove Salad: http://ice1.somafm.com/groovesalad-256-mp3
  SomaFM Lush: http://ice1.somafm.com/lush-128-mp3
  Allzic Radio R&B: http://allzic10.ice.infomaniak.ch/allzic10.mp3
  The UK 1940s Radio Station: http://91.121.134.23:8100/1

**Comment by Yocee84** [comment]
Thanks!

**Comment by tomtastic** [comment]
Thanks @MaartenSanders , if it helps anyone, here's my docker-compose.yml for use with Traefik 2.x, which I then point to with dnsmasq :
```
---
version: '2.4'
services:

  ycast:
    image: netraams/ycast-docker:v10
    container_name: ycast
    networks:
      - proxy
    expose:
      - 80
    volumes:
      - /data/docker/ycast/stations.yml:/opt/ycast/stations.yml
    mem_limit: 128m
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.ycast.entryPoints: "http"
      traefik.http.routers.ycast.service: "ycast"
      traefik.http.services.ycast.loadbalancer.server.port: 80
      traefik.http.routers.ycast.rule: "Host(`denon.vtuner.com`, `denon2.vtuner.com`, `logo.vtuner.net`)"

networks:
  proxy:
    external: true
    name: proxy
...
```

`/etc/dnsmasq.d/vtuner_to_docker_ycast.conf`
```
address=/denon.vtuner.com/192.168.0.18
address=/denon2.vtuner.com/192.168.0.18
address=/logo.vtuner.net/192.168.0.18
```
